// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsjMJXJkZIUyn64ksCmthdrCCJughtceo',
    appId: '1:671040492929:android:d09fef0514c7117c4a8480',
    messagingSenderId: '671040492929',
    projectId: 'finance-manager-c6dc5',
    storageBucket: 'finance-manager-c6dc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlRKMrzn0lq0v5gLGDJ33vMvVgzRas3sc',
    appId: '1:671040492929:ios:399205ca17a5b9bd4a8480',
    messagingSenderId: '671040492929',
    projectId: 'finance-manager-c6dc5',
    storageBucket: 'finance-manager-c6dc5.firebasestorage.app',
    iosBundleId: 'com.example.financemanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAstz-4kTyNtVN_G2W2qpxkiZiCLLJBHzY',
    appId: '1:671040492929:web:0e4c64a4c560d07e4a8480',
    messagingSenderId: '671040492929',
    projectId: 'finance-manager-c6dc5',
    authDomain: 'finance-manager-c6dc5.firebaseapp.com',
    storageBucket: 'finance-manager-c6dc5.firebasestorage.app',
    measurementId: 'G-TLM6TE668X',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAstz-4kTyNtVN_G2W2qpxkiZiCLLJBHzY',
    appId: '1:671040492929:web:7dcca62cb0f3924c4a8480',
    messagingSenderId: '671040492929',
    projectId: 'finance-manager-c6dc5',
    authDomain: 'finance-manager-c6dc5.firebaseapp.com',
    storageBucket: 'finance-manager-c6dc5.firebasestorage.app',
    measurementId: 'G-31ZQKQ6ZQ9',
  );

}